# Generated by Django 4.2.1 on 2023-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioIntelligenceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_by_model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_by_user',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_rate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Video_content',
            field=models.CharField(blank=True, null=True),
        ),
    ]
