# Generated by Django 4.2.1 on 2023-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioIntelligenceAPI', '0002_alter_useraudio_infant_cry_class_by_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraudio',
            name='class_distribution',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraudio',
            name='solutions_executed',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraudio',
            name='text',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='useraudio',
            name='user_solution',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_by_model',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_by_user',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Infant_cry_class_rate',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='useraudio',
            name='Video_content',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
